import { config } from "../config";
import { cookieToInitialState } from "@account-kit/core";
import { headers } from "next/headers";
import "./globals.css";
import { Providers } from "./providers";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const initialState = cookieToInitialState(
    config,
    headers().get("cookie")
  );

  return (
    <html lang="en" suppressHydrationWarning>
      <body className="bg-background text-foreground">
        <Providers initialState={initialState}>
          <div className="container mx-auto p-4">{children}</div>
        </Providers>
      </body>
    </html>
  );
}
